package utils;

public enum MessagesLogin {
	//*** MESSAGES ***//
	// OK
	LOGIN_TEST_START("INICIANDO PRUEBA DE LOGIN"),
	LOGIN("LOGUEANDO"),
	LOGIN_COMPLETED("LOGIN COMPLETADO"),
	LOGIN_INCORRECT_COMPLETED("LOGIN INCORRECTO COMPLETADO"),
	VALIDATE_LOGIN("VALIDANDO LOGIN"),
	VALIDATE_LOGIN_INCORRECT("VALIDANDO LOGIN INCORRECTO"),
	LOGIN_TEST_OK("PRUEBA DE LOGIN EXITOSA"),
	LOGIN_INCORRECT_TEST_OK("PRUEBA DE LOGIN INCORRECTO EXITOSA"),
	LOGIN_TEST_FINISH("FINALIZANDO PRUEBA DE LOGIN"),
	LOGIN_BTN_SAVED("BOTÓN DE LOGIN ALMACENADO"),
	LOGIN_BTN_VISIBLE("EL BOTÓN DE LOGIN ES VISIBLE"),
	
	// Error
	LOGIN_TEST_ERROR("PRUEBA DE LOGIN FALLIDA"),
	LOGIN_BTN_NOT_VISIBLE("EL BOTÓN DE LOGIN NO ES VIISBLE");
	
	/*** VARIABLES ***/
	private final String message;
	
	/*** METHODS ***/
	// Setter
	MessagesLogin(String message){
		this.message = message;
		
	}
	
	// Getter
	public String getMessage() {
		return message;
		
	}
}
