name: Run Selenium TestNG tests on dispatch

on:
  repository_dispatch:
    types: [run-selenium-dev]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install dependencies and run tests
        run: mvn clean test
        working-directory: saucedemo

      - name: Archive test reports
        uses: actions/upload-artifact@v4
        with:
          name: testng-report
          path: saucedemo/src/test/resources/reports